name: Deploy Homologação (FTP)

on:
  push:
    branches:
      - develop

jobs:
  web-deploy:
    name: Deploy Web via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Envie para a raiz do usuário de homologação
          server-dir: ./homologacao/
          port: 21
          protocol: ftps
          timeout: 60000
